### PR TITLE
Add go.mod for modules support

### PR DESCRIPTION
**Pull request by Merovius**
The go.mod and go.sum where created via running `go mod init` and `go
build`. This should enable users to use `go get` to fetch the proper
versions of all dependencies.

### CODE REVIEW

**Comment by Sheridan** [comment]
Please, update also Makefile for updating it

**Comment by Merovius** [comment]
I'm not sure what you want that to do. In general, you'd only update `go.mod` or `go.sum` if you bump dependencies to a newer version - and that's generally a manual step, because you want to specify the dependency to bump and verify the results. I guess it would be possible to add a Make-target to bump *all* dependencies to latest (which would literally just call `go get -u`). Is that what you want?

**Comment by Sheridan** [comment]
Yes, just Makefile target for update all to latest

**Comment by Merovius** [comment]
Sorry for not explicitly pinging this :) I did the addition :)

**Pull request closed without merging**
